"""Init

Revision ID: 6a7dcd1e227e
Revises: 31fc0a4df4a5
Create Date: 2023-05-08 15:37:02.175906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7dcd1e227e'
down_revision = '31fc0a4df4a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
